### ISSUE TITLE
疑有误

### ISSUE THREAD

**Issue by XiaoLingYYY** [BukkitAPI-Translation-Group/Chinese_BukkitAPI#16]
1.12.2的
org.bukkit
类 Location
getBlock方法

**Comment by andylizi** [comment]
https://github.com/BukkitAPI-Translation-Group/Chinese_BukkitAPI/commit/e64a632e4c49e48b6ce4901701571a34749a9da6#diff-5d2c7c505f1817f304c486b32ff7c742R97
https://github.com/BukkitAPI-Translation-Group/Chinese_BukkitAPI/commit/e64a632e4c49e48b6ce4901701571a34749a9da6#diff-5d2c7c505f1817f304c486b32ff7c742R75
https://github.com/BukkitAPI-Translation-Group/Chinese_BukkitAPI/commit/e64a632e4c49e48b6ce4901701571a34749a9da6#diff-5d2c7c505f1817f304c486b32ff7c742R86

两年前的翻译了。这三个恐怕都得改。

**Comment by hcrgm** [comment]
确实有问题的，同时也注意到Location类未翻译完、质量欠缺等问题，已纳入1.13的升级计划
