### ISSUE TITLE
[建议] 建议使用Java 9及以上版本生成Javadoc

### ISSUE THREAD

**Issue by DreamVoid** [BukkitAPI-Translation-Group/Chinese_BukkitAPI#32]
使用Java 9及以上版本生成的Javadoc自带搜索功能，并且[Spigot官方Javadoc](https://www.runoob.com/java/java9-new-features.html)已经这样做了，如果汉化的Javadoc也能支持搜索就更好了。
参考：[Java 9 新特性](https://www.runoob.com/java/java9-new-features.html)

**Comment by hcrgm** [comment]
曾经试过直接升java，样式会乱掉(我想保留文档现有的颜色风格)，然后没人提出我就懒得做了😏恰好最近在研究过气的深色模式，调试好了就升java 11

**Comment by DreamVoid** [comment]
> 曾经试过直接升java，样式会乱掉(我想保留文档现有的颜色风格)，然后没人提出我就懒得做了😏恰好最近在研究过气的深色模式，调试好了就升java 11

新版的 Javadoc 颜色挺好看的，和 Spigot 同步也不错
