### ISSUE TITLE
更新1.19

### ISSUE THREAD

**Issue by RanMinecraft** [BukkitAPI-Translation-Group/Chinese_BukkitAPI#39]

**Comment by prprprPro** [comment]
您的邮件已收到，我将尽快给您回复。吴 天宇苏州大学 · 纺织与服装工程学院江苏省 苏州市 干将东路178号 苏州大学北校区电话: + 86 138 6208 9022邮箱: ***@***.***
本邮件仅发给指定人员，邮件内容可能涉及保密信息，如果误发贵处请邮件通知发件人并删除此邮件，任何形式的复制、转发或散布本邮件及其内容均属违法行为。

**Comment by hcrgm** [comment]
这个月就更，敬请期待~

**Comment by hcrgm** [comment]
已更新敬请查收*^____^*
